runtime: go
api_version: go1
threadsafe: yes
service: hammer-strike-distributor

handlers:

- url: /hammer-strike/favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: _go_app

includes:
- env.yaml