runtime: go
api_version: go1
threadsafe: yes
service: default

handlers:
#root

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /index.html
  static_files: static/index.html
  upload: static/index.html

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /audio
  static_dir: static/audio

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /advanced.html
  static_files: static/advanced.html
  upload: static/advanced.html

- url: /advanced
  static_files: static/advanced.html
  upload: static/advanced.html
