apiVersion: v1
kind: Service
metadata:
  labels:
    name: hammer-strike
    visualize: "true"
  name: hammer-strike
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: hammer-strike
