apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hammer-strike-deployment
spec:
  replicas: 5
  strategy:
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: hammer-strike
        visualize: "true"
    spec:
      containers:
      - name: "hammer-strike"
        image: "gcr.io/[your project name]/hammer-strike"
        env:
        - name: LOAD_URL
          valueFrom:
            configMapKeyRef:
              name: load-url
              key: url
        livenessProbe:
            httpGet:
                path: /healthz
                port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
        ports:
        - name: "http"
          containerPort: 80
          protocol: TCP